### ISSUE TITLE
Animations are stuck for paper-checkbox and paper-toggle-button when triggered via iron-label

### ISSUE THREAD

**Issue by viftodi** [PolymerElements/iron-label#13]
### Live Demo

Example http://jsbin.com/kuqihu/1/edit?html,output
Click the label and notice how the animation is stuck.
### Steps to reproduce
1. Create an iron-label containing a paper-checkbox or paper-toggle-button
2. Click the label, observe the animations that don't complete on the checkbox/toggle-button

### Browsers Affected
I reasonably assume that this issue affects all browsers, but I have personally only tested on Chrome, Firefox and IE 11.

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [x] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
I don't think the animations don't complete: what you're seeing is the focus state, indicating that the checkbox is focused. This happens for native labels and elements as well: http://jsbin.com/hefime/edit?html,output

**Comment by viftodi** [comment]
Thank you for your response @notwaldorf 

In your demo with a native label and button it behaves the same way whether you click the button or click the label and the button get's clicked.

In the case of an iron-label there is a difference in the animation state when clicking directly the iron-checkbox/toggle-button or clicking the associated label.

Furthermore the behaviour is also different than the one when you use the (native) label of the checkbox/toggle-button, when you click that label the animation is not "stuck".

I have also tested the difference between a native checkbox with native label and native checkbox with iron-label and noticed that the native label does not retain focus after clicking the label.

Take a look here for my demo of various scenarios: http://jsbin.com/kiwuzufale/1/edit?html,output

I would really appreciate if you could take a look again into this.

Thank you.
