### ISSUE TITLE
Touch events not working

### ISSUE THREAD

**Issue by opus1269** [PolymerElements/iron-label#2]
The only part of the demo that processes Touch events correctly is the "next to" option with native elements. I tried it on both Android and Windows devices.

**Comment by cdata** [comment]
Thanks for filing an issue. We need to see a reduced test case in order to verify that there is a problem. Please re-open the issue when you have a test case, and consult our [contribution guidelines](../blob/master/CONTRIBUTING.md) for more details on filing issues!

**Comment by opus1269** [comment]
@cdata The [Demo page](https://elements.polymer-project.org/elements/iron-label?view=demo:demo/index.html&active=iron-label) demonstrates the issue, so another test case is not needed, IMO.

Detailed information:

* On Windows 10, Chrome v. 48.0.2564.103 m (two different laptops)

All the native labels work as expected with touch and mouse. The only iron-label that responds to touch events is the "label next to checkbox" example.  The others do not work (although you can see the target element's focus flash on and off sometimes as if something is being communicated). Mouse clicks work as expected. When I first posted the issue in Oct. I was on Windows 8 and the issue was the same.

* On Nexus 9 Android v. 6.0.1 Chrome v. 48.0.2564.95
* On Droid Turbo Android v. 5.1 Chrome v. 48.0.2564.95

All the native labels work as expected with touch. The only iron-label elements that responds to touch events are those associated with the native checkbox element (the first four under "iron-label-element".  The others do not work (although you can see the target element's focus flash on and off sometimes as if something is being communicated). 

* On Windows 10, Internet Explorer and Microsoft Edge, latest versions

Touch and mouse clicks work as expected.

**Comment by SPAHI4** [comment]
+1 touch events do not work with paper-checkbox, paper-toggle and others non native elements
